### ISSUE TITLE
`maxInitialWidthHint` not working for me. A col width is weird.

### ISSUE THREAD

**Issue by scriptingstudio** [validide/resizable-table-columns#23]
Hello,

I'm learning the module behaviour with the sample `resizable-table-columns/dist/samples/index.html`. There is a misprint on line 326. It should be `maxInitialWidthHint` instead of `maxInitialWidth`.
The second. I'm changing the value but the col width is always the same and equal. I expect a col width is the longest cell content.
Any ideas? 
Is it possible to remain a default width for each col?
Could you please clarify how `maxInitialWidthHint` works?

**Comment by validide** [comment]
Hi,

Thanks for spotting the misprint. 

This property is more of a "suggestion" for the component than an actual enforcement, that is why I suffixed them with `Hint`. Due to the way table column sizing works in HTML the component will try to set a width for each column that is between the `minWidth` and `maxWidth` values but no larger than the `maxInitialWidthHint`.

I believe what you are trying to achieve is supported but you will need to "double click" on the drag handle to adjust the size of the column, similar to excel.

Hope this answers your question, if it does not not please provide a sample of what you are trying to achieve.

**Comment by scriptingstudio** [comment]
There are issues I found so far
- Wrong cursor position with cell **custom padding**. The cursor suddenly jumps to the right on 30px or so. When reproducing concentrate on the very beginning of moving. Then the cursor takes a fixed shifted position while moving.
- Unpredictable column self adjusting after releasing the left button.
- Breaking table defaults. If `maxInitialWidthHint` not set columns are much wider than table defaults. Looks desperate with non resizable columns.

**Comment by validide** [comment]
I am not investing any time in developing new features or fixing any bugs at the moment. Especially since you did not provide a clear way to reproduce the issues.

If you would like you can fork the repository and play with it.
